---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: network
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  interval: 1h
  dependsOn:
    - name: sealed-secrets-controller
      namespace: kube-system
    - name: kube-prometheus-stack
      namespace: observability
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    extraArgs:
      - --enable-certificate-owner-ref=true
      - --dns01-recursive-nameservers=1.1.1.1:53
      - --dns01-recursive-nameservers-only
