---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  chart:
    spec:
      chart: loki-stack
      version: 2.0.x
      sourceRef:
        kind: HelmRepository
        name: grafana-loki-charts
        namespace: flux-system
  interval: 1h
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
  values:
    loki:
      enabled: true
      serviceMonitor:
        enabled: true

    promtail:
      enabled: true
      serviceMonitor:
        enabled: true

    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
