---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  chart:
    spec:
      chart: traefik
      version: 9.8.x
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  interval: 1h
  values:
    ports:
      web:
        redirectTo: websecure
      metrics:
        port: 8082
        protocol: TCP

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true

    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: traefik.home.tehmessiah.nl

    globalArguments:
      - --global.checknewversion=false
      - --global.sendanonymoususage=false

    additionalArguments:
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.entryPoint=metrics
