---
repos:
  - repo: local
    hooks:
      - id: eclint
        name: eclint
        language: system
        entry: eclint check
        stages:
          - commit

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.25.0
    hooks:
      - id: yamllint
        stages:
          - commit
        args: [-c=.yamllint.yaml]
