---
repos:
  - repo: local
    hooks:
      - id: eclint
        name: eclint
        language: system
        entry: eclint check
        stages:
          - commit

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.25.0
    hooks:
      - id: yamllint
        stages:
          - commit
        args: [-c=.yamllint.yaml]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck
        stages:
          - commit
        args: [-e, SC1091]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v3.0.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - "@commitlint/config-conventional"
