---
repos:
  - repo: local
    hooks:
      - id: editorconfig-checker
        name: editorconfig-checker
        language: system
        entry: editorconfig-checker
        stages:
          - commit
        args: [--config=.github/linters/.ecrc]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.25.0
    hooks:
      - id: yamllint
        stages:
          - commit
        args: [--config-file=.github/linters/.yamllint.yaml]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck
        stages:
          - commit
        args: [--color, --external-sources]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v3.0.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        args: [--config=.github/linters/.commitlintrc.yaml]
        additional_dependencies:
          - "@commitlint/config-conventional"
