---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
spec:
  chart:
    spec:
      chart: pihole
      version: 1.7.x
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
  interval: 1h
  values:
    DNS1: 1.1.1.1
    DNS2: 1.0.0.1

    # https://v.firebog.net/hosts/lists.php?type=tick
    adlists:
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
      - https://v.firebog.net/hosts/static/w3kbl.txt
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://v.firebog.net/hosts/Easylist.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
      - https://mirror1.malwaredomains.com/files/justdomains
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
      - https://www.malwaredomainlist.com/hostslist/hosts.txt
      - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
      - https://v.firebog.net/hosts/Shalla-mal.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
      - https://urlhaus.abuse.ch/downloads/hostfile/
      - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser

    extraEnvVars:
      DNSSEC: "true"

      CONDITIONAL_FORWARDING: "true"
      CONDITIONAL_FORWARDING_IP: 192.168.162.1

      TZ: Europe/Amsterdam

    persistentVolumeClaim:
      enabled: true
      storageClass: longhorn
      size: 1Gi

    serviceTCP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: dns-services
        metallb.universe.tf/allow-shared-ip: pihole-svc

    serviceUDP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: dns-services
        metallb.universe.tf/allow-shared-ip: pihole-svc

    ingress:
      enabled: true
      hosts:
        - pihole.home.tehmessiah.nl
      tls:
        - hosts:
            - pihole.home.tehmessiah.nl
          secretName: pihole.home.tehmessiah.nl-tls

      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"

        external-dns.alpha.kubernetes.io/hostname: traefik.home.tehmessiah.nl
        cert-manager.io/cluster-issuer: acme-prod

    monitoring:
      podMonitor:
        enabled: true
      sidecar:
        enabled: true
