---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: network
spec:
  chart:
    spec:
      chart: dex
      version: 2.15.x
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
  interval: 1h
  dependsOn:
    - name: sealed-secrets-controller
      namespace: kube-system
  values:
    telemetry: true
    grpc: false

    config:
      issuer: https://dex.home.tehmessiah.nl

    ingress:
      enabled: true
      hosts:
        - dex.home.tehmessiah.nl

      tls:
        - secretName: dex.home.tehmessiah.nl-tls
          hosts:
            - dex.home.tehmessiah.nl

      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"

        external-dns.alpha.kubernetes.io/hostname: dex.home.tehmessiah.nl
        cert-manager.io/cluster-issuer: acme-prod
