---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  interval: 1h
  values:
    persistence:
      defaultClassReplicaCount: 2

    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1

    defaultSettings:
      defaultReplicaCount: 2

    ingress:
      enabled: true
      host: longhorn.home.tehmessiah.nl
      tls: true
      tlsSecret: longhorn.home.tehmessiah.nl-tls

      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: network-wss-headers@kubernetescrd
        traefik.ingress.kubernetes.io/router.tls: "true"

        external-dns.alpha.kubernetes.io/hostname: longhorn.home.tehmessiah.nl
        cert-manager.io/cluster-issuer: acme-prod
