---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-gitops
  namespace: gotk-system
spec:
  path: ./namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  interval: 1m
