---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
spec:
  chart:
    spec:
      chart: pihole
      version: 1.7.x
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: gotk-system
  interval: 1h
  values:
    serviceTCP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: dns-services
        metallb.universe.tf/allow-shared-ip: pihole-svc

    serviceUDP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: dns-services
        metallb.universe.tf/allow-shared-ip: pihole-svc

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"

        external-dns.alpha.kubernetes.io/hostname: traefik.home.tehmessiah.nl
      hosts:
        - pihole.home.tehmessiah.nl
