---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 11.0.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  interval: 1h
  values:
    prometheus:
      prometheusSpec:
        retention: 6h

        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 10Gi

        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false

      ingress:
        enabled: true
        hosts:
          - prometheus.home.tehmessiah.nl
        tls:
          - hosts:
              - prometheus.home.tehmessiah.nl
            secretName: prometheus.home.tehmessiah.nl-tls

        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"

          external-dns.alpha.kubernetes.io/hostname: prometheus.home.tehmessiah.nl
          cert-manager.io/cluster-issuer: acme-prod

    grafana:
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: default
              type: file
              folder: ""
              orgId: 1
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default

      dashboards:
        default:
          cert-manager:
            url: https://gitlab.com/uneeq-oss/cert-manager-mixin/-/raw/master/dashboards/cert-manager.json
          sealed-secrets:
            url: https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/master/contrib/prometheus-mixin/dashboards/sealed-secrets-controller.json
          pihole:
            url: https://grafana.com/api/dashboards/10176/revisions/2/download
          toolkit-cluster:
            url: https://raw.githubusercontent.com/fluxcd/toolkit/main/manifests/monitoring/grafana/dashboards/cluster.json
          toolkit-control-plane:
            url: https://raw.githubusercontent.com/fluxcd/toolkit/main/manifests/monitoring/grafana/dashboards/control-plane.json

      plugins:
        - grafana-piechart-panel

      ingress:
        enabled: true
        hosts:
          - grafana.home.tehmessiah.nl
        tls:
          - hosts:
              - grafana.home.tehmessiah.nl
            secretName: grafana.home.tehmessiah.nl-tls

        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"

          external-dns.alpha.kubernetes.io/hostname: grafana.home.tehmessiah.nl
          cert-manager.io/cluster-issuer: acme-prod

    alertmanager:
      ingress:
        enabled: true
        hosts:
          - alert-manager.home.tehmessiah.nl
        tls:
          - hosts:
              - alert-manager.home.tehmessiah.nl
            secretName: alert-manager.home.tehmessiah.nl-tls

        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"

          external-dns.alpha.kubernetes.io/hostname: alert-manager.home.tehmessiah.nl
          cert-manager.io/cluster-issuer: acme-prod
