---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 11.0.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  interval: 1h
  values:
    prometheus:
      prometheusSpec:
        retention: 6h

        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 10Gi

      ingress:
        enabled: true
        hosts:
          - prometheus.home.tehmessiah.nl
        tls:
          - hosts:
              - prometheus.home.tehmessiah.nl
            secretName: prometheus.home.tehmessiah.nl-tls

        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"

          external-dns.alpha.kubernetes.io/hostname: prometheus.home.tehmessiah.nl
          cert-manager.io/cluster-issuer: acme-prod

    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.home.tehmessiah.nl
        tls:
          - hosts:
              - grafana.home.tehmessiah.nl
            secretName: grafana.home.tehmessiah.nl-tls

        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"

          external-dns.alpha.kubernetes.io/hostname: grafana.home.tehmessiah.nl
          cert-manager.io/cluster-issuer: acme-prod

    alertmanager:
      ingress:
        enabled: true
        hosts:
          - alert-manager.home.tehmessiah.nl
        tls:
          - hosts:
              - alert-manager.home.tehmessiah.nl
            secretName: alert-manager.home.tehmessiah.nl-tls

        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"

          external-dns.alpha.kubernetes.io/hostname: alert-manager.home.tehmessiah.nl
          cert-manager.io/cluster-issuer: acme-prod
