---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: kustomize-discord
  namespace: flux-system
spec:
  providerRef:
    name: kustomize-discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
