---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      version: 1.10.x
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
  interval: 1h
  values:
    image:
      # TODO: Remove this once the upstream helm chart is updated.
      tag: v0.12.6
