---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-cloudflare
  namespace: network
spec:
  encryptedData:
    cloudflare_api_token: AgAbymVmfLlnJIHtrOicDonGdS208IUYQaL1v+MXxaKWhfdx114myHYxGJPaENVX++L+R2V0ZhqXK1cC2sSRYvw/+qIy4psNJZxN0HLgxgLDzuyy3f8nHTH9roZy4WyJ9tqk6FWAK/Oh/+lVR6Q1cBOXTVlUpLpnS1GzIlTId8E6W/8bAz8Kofkd8vx7w6jic6FHVHPkUTVVh+Ltk9a/NwMDqkrIexyn+SV3eLtS3Y1HDBfihXAY2MFAmACjKMjBd28Lu8I2ONqd1MJc8qm3IaoOH0TDKU8X+R5TqPI6h3BMuSNNTHT7nqC8v5YtULRLsKwiMJErNtAo2kDvXylqxUR4eKHc9BkimPzccxlkQ7rTFyiYeTCn/P1KaYZ0edY6o/Y2lLJ7s7n5Rcdq6xNk/2r5av+habkkEkrXKcmLk+Up3m+U0xm/JebL0F2c84SpPIwgPvKnCYklInMXxHP63cgsTG2o82cw2vzTgcpA7fFPaNx2jWJGUeEA/gHFqJycdKB0vj5dFWZwMmCLhxuzVhFQvZfnTPlvdaoXe/LGOBlnY4s0Xn7C4Z2IP58b9Q/D5I2dQJU3bsCZDSvuK7jyoEcHX1a7AW98PiVV81ErIE2TNpOJwKgcEpjmNGFNofgYVecDLT+XixLhoabOAVBgnbIY6OZzRg4Ct9eaK4swWWAlNAAdzZq55JZjkJxCecLLnaGGEu4vOnqKtPb6Y/LZfGnHZUqyJa0YmEAgDi/qQk3ru8BZvoqUzoJU
  template:
    metadata:
      name: external-dns-cloudflare
      namespace: network
