---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      version: 1.12.x
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
  interval: 1h
  values:
    serviceMonitor:
      create: true
