---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: git-discord
  namespace: flux-system
spec:
  type: discord
  channel: logs-git
  username: flux-system
  secretRef:
    name: git-discord-webhook-url
