---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: git-discord
  namespace: flux-system
spec:
  providerRef:
    name: git-discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
