---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  url: https://github.com/BeeHiveJava/k8s-gitops
  ref:
    branch: main
  interval: 1m
  ignore: |
    # exclude all
    /*

    # include cluster dir
    !/cluster/

    # exclude file extensions from cluster dir
    /cluster/**/*.txt
    /cluster/**/*.md
