---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: notification-controller
  namespaceSelector:
    matchNames:
      - flux-system
  podMetricsEndpoints:
    - port: http-prom
