---
name: eclint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  eclint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run eclint
        uses: snow-actions/eclint@v1.0.1
        with:
          args: check
