---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: helm-discord
  namespace: flux-system
spec:
  providerRef:
    name: helm-discord
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: "*"
    - kind: HelmRepository
      name: "*"
